# Generated by Django 4.2 on 2023-05-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
