# Generated by Django 4.2 on 2023-05-02 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_buyer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='name',
        ),
    ]
